name: compliance

on:
  pull_request:
  push:

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install black
        run: pip install black

      - name: Run black check
        run: black --check .
